title: Daofei Zhang's Homepage
page-top-title: Daofei Zhang's Homepage
top-section-bg-text: Mathematics-Dynamical Systems and Ergodic Theory
home-subtitle: Daofei Zhang&ensp;|&ensp;张道飞
copyright-text: '&copy; Daofei Zhang 2023-2025. All Rights Reserved.'
